# Site settings
baseurl = "https://tibcosoftware.github.io/tci-awesome/"
languageCode = "en-us"
title = "Showcase of awesome projects for TIBCO Cloud Integration"
theme = "hugrid"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "tci-awesome"
    subtitle = "Showcase of awesome extensions and projects for TIBCO Cloud<sup>TM</sup> Integration"
    author = "retgits"
    description = "Showcase of awesome extensions and projects for TIBCO Cloud<sup>TM</sup> Integration"

    # Body background color
    bodybgcolor = "#f9f9f9"

    # Preview container button text
    buttontext = "Get the project"

    # Footer text
    footertext = "(c) TIBCO Software Inc."

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']
